version: 1
frontend:
  phases:
    preBuild:
      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*